### ISSUE TITLE
Python 3 support 

### ISSUE THREAD

**Issue by bufke** [thoas/django-sequere#2]
You are a liar and I'm pinging you :)

Working on a pull request, fixed a couple obvious issues. https://github.com/bufke/django-sequere. This may not be python 3 related though.

```
Python 3.4.2 (default, Jan  1 2015, 13:14:17) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from core.models import *
>>> p1 = Profile.objects.all()[0]
>>> p2 = Profile.objects.all()[1]
>>> p1.follow(p2)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/sequere/mixin.py", line 5, in follow
    return follow(self, instance)
  File "/usr/local/lib/python3.4/site-packages/sequere/models.py", line 7, in follow
    return get_backend()().follow(from_instance, to_instance)
  File "/usr/local/lib/python3.4/site-packages/sequere/backends/database/__init__.py", line 44, in follow
    to_instance=to_instance))
  File "/usr/local/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/query.py", line 424, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/query.py", line 465, in _create_object_from_params
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/django/db/models/query.py", line 457, in _create_object_from_params
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "from_identifier" violates not-null constraint
DETAIL:  Failing row contains (1, 2015-03-17 17:42:36.307382+00, 1, null, 2, null, f).
```

**Comment by thoas** [comment]
nice :+1: 

Waiting for your PR :)

Don't hesitate if the documentation is not complete, I'm available.
